name: build

on:
  workflow_dispatch:
        
jobs:
  build:
      runs-on: [ubuntu-latest]
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.ORG_DOCKERHUB_USERNAME }}
            password: ${{ secrets.ORG_DOCKERHUB_TOKEN }}
        
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              atomlab/zenb:${{ github.run_number }}
              atomlab/zenb:latest




      
        
      
